### ISSUE TITLE
Add MongoDB URI to configuration properties

### ISSUE THREAD

**Issue by JonasHavers** [e-breuninger/spring-boot-starter-breuninger#14]
You should be able to configure a MongoDB connection URI (e.g. from Mongo Atlas API) which is then used instead of individual configuration properties like host, port, ssl encryption, auth db.

Example MongoDB URI:
```
mongodb://xxx-xxx-shard-00-00-xxxxx.mongodb.net:27017,xxx-xxx-shard-00-01-xxxxx.mongodb.net:27017,xxx-xxx-shard-00-02-xxxxx.mongodb.net:27017/?ssl=true&authSource=xxx&replicaSet=xxx-xxx-shard-0
```

**Comment by BeneStem** [comment]
Using spring-data now... can configure all that stuff now :)
