### ISSUE TITLE
Add support for multiple feature classes

### ISSUE THREAD

**Issue by ldziedziul** [e-breuninger/spring-boot-starter-breuninger#16]
If you would change `FeatureProvider` bean method to accept list of `FeatureClassProvider` beans then you could use multiple enums since `GenericEnumBasedFeatureProvider` constructor allows to pass an array of the enums.
I think this could be implemented by changing bean method to something like this:
```java
        @Bean
        public FeatureProvider featureProvider(final List<FeatureClassProvider> featureClassProviders) {
            @SuppressWarnings("unchecked")
            Class<? extends Enum<?>>[] featureClasses = featureClassProviders.stream()
                    .map(FeatureClassProvider::getFeatureClass).toArray(Class[]::new);
            return new GenericEnumBasedFeatureProvider(featureClasses);
        }
```
https://github.com/e-breuninger/spring-boot-starter-breuninger/blob/fca675f5186f452e1d1a667e106fde9e0f06cc17/spring-boot-starter-breuninger-togglz/src/main/java/com/breuninger/boot/togglz/configuration/TogglzConfiguration.java#L55

**Comment by BeneStem** [comment]
Hey there, thank you for the improvement idea I will definitely consider changing it in the future :)
